# Exception_Handling

Program will throw error for various reason in run time. It called **_run-time error_** . When program show the run-time error when it run it called **_exception_** in programming. What do to when occur the run time error it called **_exception handling_** .

Table of Content :
- **[try block](#try-block)**
- **[catch block](#catch-block)**
- **[throw statement](#throw-statement)**
- **[catch all handler](#catch-all-handler)**
- **[uncaught exception](#uncaught-exception)**

## try block

In **_block_** write the statement which can probabily throw error in run time. Syntax is :

```cpp
try{
    // program statement here
}
```

<hr />
<br />

## catch block

catch block is a block of statment which run if try statement throw error in program run time. It also write after try block :

```cpp
try{
    // program  statement here
}catch(parameter){
    // exception handling
}
```

If multiple catch block :

```cpp
try{
    // program statement here
}catch(parameter){
    // exception handling
}catch(parameter){
    // exception handling
}
```

In catch block parameter determint the data type, and try block throw error spacifiy data type and run the catch block for spacifiy data type error.Here syntax :

```cpp
try{
    // program statement
}catch(int a){
    // execption handling code for int
}catch(int *){
    // exception handling code for int pointer
}
```

In here, if try block throw **_int_** type data error in that case **_int catch block_** work and if it throw **\*int \*\*** data type error then **_int \* catch blocK_** work as well.

<hr />
<br />

## throw statement

we can throw our error in try block to catch block by **_throw_** keyword. Here syntax :

```cpp
throw execption;
```

Here example :
**_Program : try catch throw_**

```cpp
#include <iostream>

using namespace std;

// here a function which throw the error
void throw_error(void){
    int n = 30;
    throw n;
}

int main(void){
    try{
        throw_error();
    }catch(int){
        cout << "we caought the int type error :(" << endl;
    }

    return 0;
}
```

**_Output : try catch throw_**

```
we caought the int type error :(
```

<hr />
<br />

## catch all handler

If we want to handle all kind of error in one catch block then use **_..._** operator in catch block parameter. Here syntax :

```cpp
try{
    // program statment
}catch(...){
    // handle the all kind of error in one catch block
}
```

**_Program : catch all handler_**

```cpp
#include <iostream>

using namespace std;


int main(void){
    try{
        // its a error
        double a = 30;
        throw a;
    }catch(...){
        cout << "Something is wrong :(" << endl;
    }
    return 0;
}
```

**_Output : catch all handler_**

```
Something is wrong :(
```

<hr />
<br />

## uncaught exception

if a error can not caought by **_catch_** block it called **_uncaught exception_** . In that case compiler call **_terminate()_** function from standard library and **_terminate()_** function call **_abort()_** function to finish the program.


<hr />
<br />

[< OLD README](./../README.md)
-------